apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-canary-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        env: production
        color: blue
        type: canary
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1
        ports:
        - containerPort: 80
