apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-green-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        env: production
        color: green
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.1
        ports:
        - containerPort: 80
